// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `Demo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.zeroc.api;

public interface DemoProviderPrx extends Ice.ObjectPrx
{
    public String sayHelo(int parInt, String parStr);

    public String sayHelo(int parInt, String parStr, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sayHelo(int parInt, String parStr);

    public Ice.AsyncResult begin_sayHelo(int parInt, String parStr, java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_sayHelo(int parInt, String parStr, Ice.Callback __cb);

    public Ice.AsyncResult begin_sayHelo(int parInt, String parStr, java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_sayHelo(int parInt, String parStr, Callback_DemoProvider_sayHelo __cb);

    public Ice.AsyncResult begin_sayHelo(int parInt, String parStr, java.util.Map<String, String> __ctx, Callback_DemoProvider_sayHelo __cb);

    public Ice.AsyncResult begin_sayHelo(int parInt, 
                                         String parStr, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sayHelo(int parInt, 
                                         String parStr, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_sayHelo(int parInt, 
                                         String parStr, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_sayHelo(int parInt, 
                                         String parStr, 
                                         java.util.Map<String, String> __ctx, 
                                         IceInternal.Functional_GenericCallback1<String> __responseCb, 
                                         IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                         IceInternal.Functional_BoolCallback __sentCb);

    public String end_sayHelo(Ice.AsyncResult __result);
}
