// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.3
//
// <auto-generated>
//
// Generated from file `Demo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.zeroc.api;

public interface PrintProvider extends Ice.Object,
                                       _PrintProviderOperations, _PrintProviderOperationsNC
{
    public static final String ice_staticId = "::com::zeroc::api::PrintProvider";

    public static final long serialVersionUID = 921949589L;
}
